### ISSUE TITLE
1:m or m:m relationships

### ISSUE THREAD

**Issue by blue995** [RiceKab/sqlalchemy-seeder#4]
Is it possible to define multiple references to other entities?

In this example i want to define a 1:m relationship (1 Object has n images)

```
[
  {
    "target_class": "database.model:Image",
    "data": [
      {
        "path": "path/to/some/picture",
        "title": "01"
      }
    ]
  },
  {
    "target_class": "database.model:ImageContainer",
    "data": [
      {
        "id": 1,
        "!refs": {
          "images": {
            "target_class": "database.model:Image",
            "criteria": {
              "title": "01"
            }
          }
        }
      }
    ]
  }
]
```

When i try to read the new entities from the json file i get the following type error:
`TypeError: Incompatible collection type: Image is not list-like`

Thats because my ImageContainer object expects a list of Image objects as image property.
I couldn't find anything in the documentation about this topic and i tried several things to make it work. Do you have any suggestions or is it not implemented yet?

**Comment by RiceKab** [comment]
You are correct in that there is currently no support for defining a list of referenced entities on the list side. 

I actually had an implementation for this in the original release but it was extremely confusing to use so I dropped it until I could find a better solution for it. 

### If you need a solution now (0.3.0)

You can define **1-N** by specifying the reference on the many side. So in your example there must be a something like a `container_id` field in the `Image` class (and maybe a `ImageContainer` relationship as well). If you switch it around that'll work fine:

```
[
  {
    "target_class": "database.model:Image",
    "data": [
      {
        "path": "path/to/some/picture",
        "title": "01",
        "!refs": {
          "container_id": {
            "target_class": "database.model:ImageContainer",
            "criteria": {
              "id": 1
            },
            "field": "id"
          }
        }
      }
    ]
  },
  {
    "target_class": "database.model:ImageContainer",
    "data": [
      {
        "id": 1
      }
    ]
  }
]
```

Or the YAML equivalent:

```
---
- target_class: database.model:Image
  data:
  - path: path/to/some/picture
    title: '01'
    "!refs":
      container_id:
        target_class: database.model:ImageContainer
        criteria:
          id: 1
        field: id
- target_class: database.model:ImageContainer
  data:
  - id: 1
```

**N-M** relationships are currently not supported at all unfortunately. The impedance there is mainly on the design of the data schema.

### In the future (0.4.x or later)

The main problem lies with how to provide a clean way to define criteria. Currently all criteria are checked for equality only which makes using the filter (as they are in 0.3.0) extremely cumbersome. For example, if you want an ImageContainer to contain all Image entities with the word "cat" in the title you'd have to create a reference block for each image, matching the title or id exactly. 

Coincidentally I was planning on finishing the 0.4.0 release this weekend, which I think is a step in the right direction to define references more cleanly. Then you could use ids to explicitly define which entities belong in the list. So with the new format it would look something like this:
```
{
    "!models": ["database.model"],
    "Image": [
        {
            "!id": "image01",
            "title": "01",
            "path": "/path/to/file"
        },
        {
            "!id": "image02",
            "title": "02",
            "path": "/path/to/file"
        },
        {
            "!id": "image03",
            "title": "03",
            "path": "/path/to/file"
        }
    ],
    "ImageContainer": {{
            "id": 1,
            "images": ["#image01", "#image03"]
    }
}
```

Or in YAML:
```
---
"!models":
- database.model
Image:
- "!id": image01
  title: '01'
  path: "/path/to/file"
- "!id": image02
  title: '02'
  path: "/path/to/file"
- "!id": image03
  title: '03'
  path: "/path/to/file"
ImageContainer:
  id: 1
  images:
  - "#image01"
  - "#image03"
```

This doesn't solve the problem of letting you define more intiricate criteria (eg.: "all images with a title that contain the word 'cat'") but it does at least remove essentially copying your entity definition in a reference block.
